### PR TITLE
Add support for the Khan.Range tween style

### PR DESCRIPTION
**Pull request by stephenprater**

### CODE REVIEW

**Comment by cmhobbs** [comment]
Bring me your tests...

**Comment by cmhobbs** [comment]
Tests aside, code looks fine.

**Comment by JamesChristie** [comment]
I concur with tests, if only some arbitrary cases at the integration level. Otherwise, that's pretty nifty.

**Comment by Robovirtuoso** [comment]
What is the use case for Khan.Range? Some documentation would be helpful :)

**Comment by stephenprater** [comment]
Tests provided, switched to Mocha & Chai.

Somebody should really do something about the timeouts.  I'm not sure what the best solution to testing these sort of time-dependent functions is.  Mock the timers seems like a pretty good approach, but it's sooooo labor intensive.  I miss jasmine's waitFor.

**Pull request closed without merging**
